//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StoreDomain
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentBillProduct
    {
        public int PaymentBillID { get; set; }
        public Nullable<int> PaymentId { get; set; }
        public Nullable<int> ProductId { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public int Status { get; set; }
    
        public virtual PaymentBill PaymentBill { get; set; }
        public virtual Users Users { get; set; }
        public virtual Product Product { get; set; }
    }
}
