//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StoreDomain
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class MobileStoreEntities : DbContext
    {
        public MobileStoreEntities()
            : base("name=MobileStoreEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Category> Category { get; set; }
        public virtual DbSet<Color> Color { get; set; }
        public virtual DbSet<PaymentBill> PaymentBill { get; set; }
        public virtual DbSet<PaymentBillProduct> PaymentBillProduct { get; set; }
        public virtual DbSet<Product> Product { get; set; }
        public virtual DbSet<ProductQuantity> ProductQuantity { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<Vendor> Vendor { get; set; }
    
        public virtual ObjectResult<spGetProductDetails_Result> spGetProductDetails()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spGetProductDetails_Result>("spGetProductDetails");
        }
    }
}
